# -*- coding: utf-8 -*-
"""mikołaj.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1j9qMDLRmx3DDDsD7iSUPgQLJQzHBCY4u
"""

import streamlit as st
import matplotlib.pyplot as plt
import matplotlib.patches as patches
import numpy as np

def narysuj_mikolaja():
    # Inicjalizacja figury (figura jest zwracana, aby Streamlit mógł ją odebrać)
    fig, ax = plt.subplots(figsize=(6, 8))

    # Ustawienia osi
    ax.set_xlim(-10, 10)
    ax.set_ylim(-10, 10)
    ax.set_aspect('equal', adjustable='box')
    ax.axis('off') # Ukrycie ramek i etykiet osi

    # --- Kolory ---
    kolor_czerwony = '#D93025'
    kolor_cialo = '#FDD9C2'
    kolor_bialy_futro = '#F0F0F0'
    kolor_czarny = '#1A1A1A'

    # --- Rysowanie: Głowa (koło) ---
    glowa = patches.Circle((0, 3), radius=2, facecolor=kolor_cialo, edgecolor=kolor_czarny, linewidth=1.5)
    ax.add_patch(glowa)

    # --- Rysowanie: Czapka i Broda ---
    # Opaska futrzana (prostokąt)
    opaska_futrzana = patches.Rectangle((-2.5, 4.5), 5, 0.5, facecolor=kolor_bialy_futro, edgecolor=kolor_czarny, linewidth=1.5)
    ax.add_patch(opaska_futrzana)

    # Czerwona część (Polygon)
    punkty_czapki = np.array([(1.5, 6.5), (1.5, 5), (-1.5, 5)])
    czapka_czerwona = patches.Polygon(punkty_czapki, closed=True, facecolor=kolor_czerwony, edgecolor=kolor_czarny, linewidth=1.5)
    ax.add_patch(czapka_czerwona)

    # Pompon (koło)
    pompon = patches.Circle((1.5, 6.5), radius=0.5, facecolor=kolor_bialy_futro, edgecolor=kolor_czarny, linewidth=1)
    ax.add_patch(pompon)

    # Broda (Elipsa)
    broda = patches.Ellipse((0, 1.5), width=4, height=3, facecolor=kolor_bialy_futro, edgecolor=kolor_czarny, linewidth=1.5, zorder=1)
    ax.add_patch(broda)

    # --- Rysowanie: Ciało i Pas ---
    cialo = patches.Rectangle((-3, -6), 6, 8, facecolor=kolor_czerwony, edgecolor=kolor_czarny, linewidth=1.5, zorder=0)
    ax.add_patch(cialo)

    pas_czarny = patches.Rectangle((-3.5, -0.5), 7, 1, facecolor=kolor_czarny, zorder=2)
    ax.add_patch(pas_czarny)

    klamra = patches.Rectangle((-1, -0.25), 2, 0.5, facecolor='#FFD700', edgecolor=kolor_czarny, linewidth=1, zorder=3)
    ax.add_patch(klamra)

    # Dodanie oczu (które pominąłem w poprzednich wersjach, a powinny być)
    oko_lewe = patches.Circle((-0.7, 3.5), radius=0.2, facecolor=kolor_czarny)
    oko_prawe = patches.Circle((0.7, 3.5), radius=0.2, facecolor=kolor_czarny)
    ax.add_patch(oko_lewe)
    ax.add_patch(oko_prawe)

    # Nos
    nos = patches.Circle((0, 3), radius=0.3, facecolor=kolor_cialo, edgecolor=kolor_czarny, linewidth=0.5)
    ax.add_patch(nos)

    # --- Finalizacja ---
    plt.title("Wesoły Mikołaj")

    # Zwrócenie obiektu figury (a nie wywołanie plt.show())
    return fig

# --- Główna sekcja Streamlit ---
st.title("🎅 Generator Mikołaja Matplotlib w Streamlit")

# Użycie funkcji Streamlit do wyświetlenia figury
st.pyplot(narysuj_mikolaja())